# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 07:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(max_length=3, null=True)),
                ('nationality', models.CharField(max_length=100, null=True)),
                ('player_league', models.CharField(max_length=100, null=True)),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='playerteams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['player_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.TextField()),
                ('manager', models.TextField()),
                ('league', models.TextField()),
                ('location', models.TextField()),
                ('team_titles', models.IntegerField(default=0, null=True)),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='teamplayers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.Team'),
        ),
    ]
