# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 07:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapi', '0003_auto_20160403_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='player',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='playerteams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='teamplayers', to=settings.AUTH_USER_MODEL),
        ),
    ]
