engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - app/**
exclude_paths:
- test/spec/**/*
- app/scripts/material.min.js
- app/scripts/material.min.js.map
- app/styles/material.min.css