# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20160311_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
