# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20160311_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='fouls',
        ),
        migrations.AddField(
            model_name='player',
            name='fouls_pg',
            field=models.FloatField(null=True),
        ),
    ]
