# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attacker',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.Player')),
                ('key_passes_pg', models.FloatField(null=True)),
                ('shots_pg', models.FloatField(null=True)),
                ('dripples_pg', models.FloatField(null=True)),
            ],
            bases=('search.player',),
        ),
        migrations.CreateModel(
            name='Defender',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.Player')),
                ('tackles', models.IntegerField(null=True)),
                ('clearances', models.FloatField(null=True)),
                ('interceptions_pg', models.FloatField(null=True)),
            ],
            bases=('search.player',),
        ),
        migrations.CreateModel(
            name='Midfielder',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='search.Player')),
                ('tackles', models.IntegerField(null=True)),
                ('key_passes_pg', models.FloatField(null=True)),
                ('shots_pg', models.FloatField(null=True)),
                ('dripples_pg', models.FloatField(null=True)),
            ],
            bases=('search.player',),
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='appearances',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fouls',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player_league',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='red_cards',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='yellow_cards',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_titles',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
