# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20160311_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attacker',
            old_name='dripples_pg',
            new_name='dripples_per_game',
        ),
        migrations.RenameField(
            model_name='attacker',
            old_name='key_passes_pg',
            new_name='key_passes_per_game',
        ),
        migrations.RenameField(
            model_name='attacker',
            old_name='shots_pg',
            new_name='shots_per_game',
        ),
        migrations.RenameField(
            model_name='defender',
            old_name='interceptions_pg',
            new_name='interceptions_per_game',
        ),
        migrations.RenameField(
            model_name='midfielder',
            old_name='dripples_pg',
            new_name='dripples_per_game',
        ),
        migrations.RenameField(
            model_name='midfielder',
            old_name='key_passes_pg',
            new_name='key_passes_per_game',
        ),
        migrations.RenameField(
            model_name='midfielder',
            old_name='shots_pg',
            new_name='shots_per_game',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='fouls_pg',
            new_name='fouls_per_game',
        ),
    ]
